/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizza;

import javax.swing.JLayeredPane;

/**
 *
 * @author Anonymous
 */
public class DashboardFrame extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    private PizzaParlor parlor;
    private Customer currentCustomer;
    
    public DashboardFrame() {
        initComponents();
    }

    DashboardFrame(PizzaParlor parlor, Customer currentCustomer) {
        initComponents();
        this.parlor=parlor;
        this.currentCustomer=currentCustomer;
        jParlorNameLabel.setText(parlor.getName());
        jParlorAddressLabel.setText(parlor.getAddress());
        jUsernameLabel.setText(currentCustomer.getUsername());
        jLayeredPane.add(jCheesePic, 0);
        jLayeredPane.add(jPepperoniPic, 0);
        jLayeredPane.add(jMushroomPic, 0);
        jPepperoniPic.setLocation(0, 12);
        jMushroomPic.setLocation(0, 12);
        jMushroomPic.setVisible(false);
        jPepperoniPic.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sizeGroup = new javax.swing.ButtonGroup();
        toppingsGroup = new javax.swing.ButtonGroup();
        jUsernameLabel = new javax.swing.JLabel();
        jParlorNameLabel = new javax.swing.JLabel();
        jLogoLabel = new javax.swing.JLabel();
        jParlorAddressLabel = new javax.swing.JLabel();
        jSmallRadio = new javax.swing.JRadioButton();
        jMediumRadio = new javax.swing.JRadioButton();
        jLargeRadio = new javax.swing.JRadioButton();
        jSizeLabel = new javax.swing.JLabel();
        jCheckOutButton = new javax.swing.JButton();
        jToppingsLabel = new javax.swing.JLabel();
        jPepperoniBox = new java.awt.Checkbox();
        jMushroomBox = new java.awt.Checkbox();
        jLayeredPane = new javax.swing.JLayeredPane();
        jCheesePic = new javax.swing.JLabel();
        jMushroomPic = new javax.swing.JLabel();
        jPepperoniPic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jUsernameLabel.setText("Customer Name");

        jParlorNameLabel.setText("Parlor Name");

        jLogoLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Anonymous\\Documents\\NetBeansProjects\\Pizza\\src\\pizza\\logo.png")); // NOI18N

        jParlorAddressLabel.setText("Parlor Address");

        sizeGroup.add(jSmallRadio);
        jSmallRadio.setText("Small");

        sizeGroup.add(jMediumRadio);
        jMediumRadio.setText("Medium");

        sizeGroup.add(jLargeRadio);
        jLargeRadio.setText("Large");

        jSizeLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jSizeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jSizeLabel.setText("Size");

        jCheckOutButton.setText("Check Out");
        jCheckOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckOutButtonActionPerformed(evt);
            }
        });

        jToppingsLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jToppingsLabel.setText("Toppings");

        jPepperoniBox.setLabel("Pepperoni");
        jPepperoniBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPepperoniBoxMousePressed(evt);
            }
        });

        jMushroomBox.setLabel("Mushrooms");
        jMushroomBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMushroomBoxMousePressed(evt);
            }
        });

        jCheesePic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizza/cheese.png"))); // NOI18N

        jMushroomPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizza/mushrooms.png"))); // NOI18N
        jMushroomPic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMushroomPicMousePressed(evt);
            }
        });

        jPepperoniPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizza/pepperoni.png"))); // NOI18N

        jLayeredPane.setLayer(jCheesePic, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane.setLayer(jMushroomPic, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane.setLayer(jPepperoniPic, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPaneLayout = new javax.swing.GroupLayout(jLayeredPane);
        jLayeredPane.setLayout(jLayeredPaneLayout);
        jLayeredPaneLayout.setHorizontalGroup(
            jLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneLayout.createSequentialGroup()
                .addComponent(jCheesePic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jMushroomPic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPepperoniPic)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPaneLayout.setVerticalGroup(
            jLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneLayout.createSequentialGroup()
                .addGroup(jLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPepperoniPic)
                    .addGroup(jLayeredPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jMushroomPic)
                            .addComponent(jCheesePic))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(jCheckOutButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLogoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jParlorAddressLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jParlorNameLabel)
                                .addGap(12, 12, 12))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSmallRadio)
                            .addComponent(jMediumRadio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLargeRadio)
                            .addComponent(jSizeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToppingsLabel)
                            .addComponent(jPepperoniBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jMushroomBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jUsernameLabel)
                        .addGap(10, 10, 10))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jParlorNameLabel)
                            .addComponent(jUsernameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jParlorAddressLabel)
                        .addGap(5, 5, 5)
                        .addComponent(jLayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLogoLabel)
                                        .addGap(23, 23, 23)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jSizeLabel)
                                            .addComponent(jToppingsLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSmallRadio))
                                    .addComponent(jPepperoniBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, 0)
                                .addComponent(jMediumRadio))
                            .addComponent(jMushroomBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(jLargeRadio)
                        .addGap(156, 156, 156)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jCheckOutButton)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckOutButtonActionPerformed

    }//GEN-LAST:event_jCheckOutButtonActionPerformed

    private void jPepperoniBoxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPepperoniBoxMousePressed
        // TODO add your handling code here:
        if (!jPepperoniBox.getState()) {
            jPepperoniPic.setVisible(true);
            if(jPepperoniPic.isVisible()){
                System.out.println("should work");
                System.out.println(jCheesePic.getLocation());
                System.out.println(jPepperoniPic.getLocation());
            }
        } else {
            jPepperoniPic.setVisible(false);
        }
    }//GEN-LAST:event_jPepperoniBoxMousePressed

    private void jMushroomPicMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMushroomPicMousePressed

    }//GEN-LAST:event_jMushroomPicMousePressed

    private void jMushroomBoxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMushroomBoxMousePressed
        // TODO add your handling code here:
        if (!jMushroomBox.getState()) {
            jMushroomPic.setVisible(true);
            System.out.println("rip");
            System.out.println(jMushroomPic.getLocation());

        } else {
            System.out.println("wtf");
            jMushroomPic.setVisible(false);
        }
    }//GEN-LAST:event_jMushroomBoxMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCheckOutButton;
    private javax.swing.JLabel jCheesePic;
    private javax.swing.JRadioButton jLargeRadio;
    private javax.swing.JLayeredPane jLayeredPane;
    private javax.swing.JLabel jLogoLabel;
    private javax.swing.JRadioButton jMediumRadio;
    private java.awt.Checkbox jMushroomBox;
    private javax.swing.JLabel jMushroomPic;
    private javax.swing.JLabel jParlorAddressLabel;
    private javax.swing.JLabel jParlorNameLabel;
    private java.awt.Checkbox jPepperoniBox;
    private javax.swing.JLabel jPepperoniPic;
    private javax.swing.JLabel jSizeLabel;
    private javax.swing.JRadioButton jSmallRadio;
    private javax.swing.JLabel jToppingsLabel;
    private javax.swing.JLabel jUsernameLabel;
    private javax.swing.ButtonGroup sizeGroup;
    private javax.swing.ButtonGroup toppingsGroup;
    // End of variables declaration//GEN-END:variables
}
