/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizza;

/**
 *
 * @author Anonymous
 */
public class DashboardFrame extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    private PizzaParlor parlor;
    private Customer currentCustomer;
    
    public DashboardFrame() {
        initComponents();
    }

    DashboardFrame(PizzaParlor parlor, Customer currentCustomer) {
        initComponents();
        this.parlor=parlor;
        this.currentCustomer=currentCustomer;
        jParlorNameLabel.setText(parlor.getName());
        jParlorAddressLabel.setText(parlor.getAddress());
        jUsernameLabel.setText(currentCustomer.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sizeGroup = new javax.swing.ButtonGroup();
        toppingsGroup = new javax.swing.ButtonGroup();
        jUsernameLabel = new javax.swing.JLabel();
        jParlorNameLabel = new javax.swing.JLabel();
        jLogoLabel = new javax.swing.JLabel();
        jParlorAddressLabel = new javax.swing.JLabel();
        jSmallRadio = new javax.swing.JRadioButton();
        jMediumRadio = new javax.swing.JRadioButton();
        jLargeRadio = new javax.swing.JRadioButton();
        jSizeLabel = new javax.swing.JLabel();
        jCheckOutButton = new javax.swing.JButton();
        jCheeseBox = new javax.swing.JCheckBox();
        jPepperoniBox = new javax.swing.JCheckBox();
        jBaconBox = new javax.swing.JCheckBox();
        jOnionBox = new javax.swing.JCheckBox();
        jMushroomBox = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jUsernameLabel.setText("Customer Name");

        jParlorNameLabel.setText("Parlor Name");

        jLogoLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Anonymous\\Documents\\NetBeansProjects\\Pizza\\src\\pizza\\logo.png")); // NOI18N

        jParlorAddressLabel.setText("Parlor Address");

        sizeGroup.add(jSmallRadio);
        jSmallRadio.setText("Small");

        sizeGroup.add(jMediumRadio);
        jMediumRadio.setText("Medium");

        sizeGroup.add(jLargeRadio);
        jLargeRadio.setText("Large");

        jSizeLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jSizeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jSizeLabel.setText("Size");

        jCheckOutButton.setText("Check Out");
        jCheckOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckOutButtonActionPerformed(evt);
            }
        });

        jCheeseBox.setText("Cheese");

        jPepperoniBox.setText("Pepperoni");

        jBaconBox.setText("Bacon");

        jOnionBox.setText("Onions");

        jMushroomBox.setText("Mushrooms");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Toppings");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLogoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jParlorAddressLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jParlorNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jUsernameLabel))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSmallRadio)
                                    .addComponent(jMediumRadio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLargeRadio)
                                    .addComponent(jSizeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(82, 82, 82)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPepperoniBox)
                                    .addComponent(jBaconBox)
                                    .addComponent(jOnionBox)
                                    .addComponent(jMushroomBox)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1)
                                        .addComponent(jCheeseBox))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(jCheckOutButton)))
                        .addGap(0, 198, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLogoLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jParlorNameLabel)
                            .addComponent(jUsernameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jParlorAddressLabel)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSizeLabel)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSmallRadio)
                    .addComponent(jCheeseBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMediumRadio)
                    .addComponent(jPepperoniBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLargeRadio)
                    .addComponent(jBaconBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jOnionBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jMushroomBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckOutButton)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckOutButtonActionPerformed

    }//GEN-LAST:event_jCheckOutButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jBaconBox;
    private javax.swing.JButton jCheckOutButton;
    private javax.swing.JCheckBox jCheeseBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jLargeRadio;
    private javax.swing.JLabel jLogoLabel;
    private javax.swing.JRadioButton jMediumRadio;
    private javax.swing.JCheckBox jMushroomBox;
    private javax.swing.JCheckBox jOnionBox;
    private javax.swing.JLabel jParlorAddressLabel;
    private javax.swing.JLabel jParlorNameLabel;
    private javax.swing.JCheckBox jPepperoniBox;
    private javax.swing.JLabel jSizeLabel;
    private javax.swing.JRadioButton jSmallRadio;
    private javax.swing.JLabel jUsernameLabel;
    private javax.swing.ButtonGroup sizeGroup;
    private javax.swing.ButtonGroup toppingsGroup;
    // End of variables declaration//GEN-END:variables
}
